export {
  addContactDetailRow,
  buildClientsAndFarmsDisplay,
  buildClientsAndFarmsInlineSegments,
  buildClientsAndFarmsInlineText,
  buildContactTableRows,
  contactDetailRowSchema,
  contactFormCategoryIdsSchema,
  contactFormDataToSubContactCreateAndLink,
  contactFormMapDataSchema,
  contactToFarmFormData,
  createDefaultContactDetails,
  createEmptyContactDetailRow,
  ensureLockedCategoryIds,
  farmFormDataToUpdatePayload,
  formatContactDisplayLabel,
  formatSecondaryContactNames,
  getContactDetailsErrorMessage,
  getFarmManagementDisplayNames,
  getFarmManagementExtraCount,
  getFarmManagementIdFromFilters,
  getLockedClientContactCategoryIds,
  getPrimaryContactDetail,
  getPrimaryContactDisplayName,
  getPrimaryFarmManagementName,
  hydrateContactDetailsForForm,
  isFarmManagementContact,
  mapApiContactDetailsToForm,
  mapContactDetailsToApi,
  mapContactFormVertices,
  normalizeContactDetailRows,
  normalizeContactInfoForClientsAndFarms,
  orderContactDetailsForApiWrite,
  parseFarmManagementContactRef,
  parseFarmManagementContactRefs,
  preserveLegacyHomePhone,
  removeContactDetailRow,
  setPrimaryDetail,
  subContactCreateAndLinkToContactCreate,
  syncLegacyFieldsFromDetails,
  toggleExpandedParentId,
  truncateClientsAndFarmsLabel,
  updateContactDetailRow,
  validateContactDetails,
} from "./lib";
export type {
  ClientsAndFarmsDisplay,
  ClientsAndFarmsDisplayInput,
  ClientsAndFarmsInlineSegment,
  ContactDetailFormRow,
  ContactTableRow,
  FarmManagementContactSummary,
  ParsedFarmManagementContactRef,
} from "./lib";
export {
  ADD_FARM_CONTACT_TITLE,
  CLIENT_CONTACT_CATEGORY_NAME,
  CONTACT_FIELD_LIMITS,
  CONTACT_SUBTYPE,
  CONTACT_TYPE_LABELS,
  DEFAULT_CONTACT_FORM_DATA,
  DEFAULT_FARM_CONTACT_FORM_DATA,
  FARM_CONTACT_BADGE_LABEL,
  FARM_CONTACT_INFO_TAB,
  FARM_FORM_FIELD_LABEL_CLASS,
  FARM_MANAGEMENT_CONTACT_LABEL,
  MAX_SUB_CONTACTS,
  SUB_CONTACTS_LINK_DESCRIPTION,
  SUB_CONTACTS_PENDING_DESCRIPTION,
  SUB_CONTACTS_TAB,
  SUB_CONTACT_PICKER_LIST_FILTERS,
  getPendingExistingSubContactIds,
  getPendingNewSubContactEntries,
  pendingSubContactCategories,
  pendingSubContactDisplayName,
  pendingSubContactKey,
  toPendingSubContactTableRow,
} from "./model";
export type {
  ContactFormData,
  FarmContactFormData,
  PendingSubContactEntry,
  PendingSubContactTableRow,
} from "./model";
export {
  AddContactFormFields,
  AddContactModal,
  AddContactToolbar,
  AddOnSiteOperationModal,
  AddPendingSubContactDialog,
  CONTACT_PAGE_TABS,
  CategoriesTab,
  CategoryDialog,
  ClientsAndFarmsCardField,
  ClientsAndFarmsCell,
  ContactCategoryDropdown,
  ContactDetailDialog,
  ContactDetailsEditor,
  ContactFormErrorSummary,
  ContactNumberRow,
  ContactsBreadcrumbToolbar,
  ContactsTable,
  FarmContactModal,
  FarmManagementContactCell,
  PendingSubContactsTab,
  SUB_CONTACT_CREATE_FORM_BODY_CLASS,
  SUB_CONTACT_CREATE_FORM_DIALOG_CLASS,
  SUB_CONTACT_CREATE_FORM_MODAL_CLASS,
  SUB_CONTACT_DIALOG_CONTENT_CLASS,
  SUB_CONTACT_DIALOG_MODAL_CLASS,
  StakeholderHeaderBadges,
  SubContactCreateContactForm,
  SubContactNewContactFields,
  SubContactSearchPicker,
} from "./ui";
export type {
  AddContactFormFieldsProps,
  AddContactModalProps,
  AddContactToolbarProps,
  CategoriesTabProps,
  CategoryDialogProps,
  ContactPageTab,
  ContactTypeBadgeContactInfo,
  ContactsBreadcrumbToolbarProps,
  ContactsTableProps,
  FarmContactModalProps,
  StakeholderHeaderBadgeContactInfo,
} from "./ui";

export { buildContactCreatePayload } from "./lib/build-contact-create-payload";
export { buildContactUpdatePayload } from "./lib/build-contact-update-payload";
export {
  buildContactFormSchema,
  type BuildContactFormSchemaOptions,
} from "./lib/build-contact-form-schema";
export {
  buildFarmContactFormSchema,
  type BuildFarmContactFormSchemaOptions,
} from "./lib/farmContactFormSchema";
export {
  contactFormValidation,
  isContactFormSubmittable,
  mapContactFormZodErrors,
} from "./lib/contact-form-validation";
export {
  getContactDetailTabs,
  isClientContact,
  CONTACT_DETAIL_TAB_CONTACT,
  CONTACT_DETAIL_TAB_FARMS,
  CONTACT_DETAIL_TAB_JOBS,
} from "./lib/contact-detail-tabs";
export { fromLocationPoint, toLocationPoint } from "./lib/contact-location";
