import { StyleSheet } from "@react-pdf/renderer";

export const maintenanceLogPdfStyles = StyleSheet.create({
  page: {
    padding: 32,
    fontFamily: "Helvetica",
    fontSize: 12,
    backgroundColor: "#fff",
    minHeight: "100%",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 0,
    alignItems: "flex-start",
  },
  logo: {
    width: 80,
    height: 80,
    objectFit: "contain",
    margin: 4,
  },
  noLogo: {
    width: 80,
    height: 80,
    margin: 4,
    borderWidth: 1,
    borderColor: "#ccc",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  noLogoText: {
    color: "#666",
  },
  maintenanceTitle: {
    backgroundColor: "#40C351",
    color: "#fff",
    padding: "24px 40px 8px 40px",
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    minWidth: 260,
    fontSize: 32,
    fontWeight: "bold",
    boxShadow: "0 2px 8px rgba(0,0,0,0.04)",
    marginBottom: 0,
  },
  equipmentInfo: {
    marginBottom: 4,
    padding: "8px 8px 8px 8px",
    marginLeft: 8,
    marginTop: 0,
  },
  equipmentName: {
    fontSize: 32,
    fontWeight: "bold",
    marginBottom: 8,
    fontFamily: "Helvetica",
  },
  equipmentDetail: {
    fontSize: 18,
    marginBottom: 4,
  },
  table: {
    width: "100%",
    marginTop: 16,
    borderWidth: 1.5,
    borderColor: "#40C351",
    borderRadius: 10,
    overflow: "hidden",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#40C351",
    color: "#fff",
    minHeight: 40,
  },
  th: {
    fontWeight: "bold",
    color: "#fff",
    padding: 12,
    fontSize: 18,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRightWidth: 0,
  },
  thDate: {
    width: "15%",
    minWidth: 80,
  },
  thDesc: {
    width: "60%",
  },
  thAssigned: {
    width: "25%",
  },
  tableRow: {
    flexDirection: "row",
    backgroundColor: "#f7f7f7",
    color: "#000",
    minHeight: 45,
    alignItems: "stretch",
  },
  tableRowEven: {
    flexDirection: "row",
    backgroundColor: "#e7e7e7",
    color: "#000",
    minHeight: 45,
    alignItems: "stretch",
  },
  td: {
    padding: 10,
    fontSize: 12,
    borderRightWidth: 0,
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "flex-start",
  },
  tdDate: {
    width: "15%",
    minWidth: 80,
    fontSize: 11,
  },
  tdDesc: {
    width: "60%",
    paddingRight: 8,
    paddingLeft: 10,
    paddingTop: 10,
    paddingBottom: 10,
    minHeight: 45,
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
  },
  tdAssigned: {
    width: "25%",
  },
  descText: {
    fontSize: 12,
    lineHeight: 1.6,
    textAlign: "left",
    flex: 1,
    flexWrap: "wrap",
  },
  footer: {
    marginTop: "auto",
    paddingTop: 20,
    flexDirection: "column",
    fontSize: 10,
    color: "#888",
  },
  footerBar: {
    backgroundColor: "#40C351",
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    padding: 12,
    color: "#fff",
  },
  footerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  footerLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  ffLogo: {
    width: 32,
    height: 32,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 4,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  ffLogoText: {
    fontSize: 12,
    color: "#fff",
  },
  footerRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  emailIcon: {
    width: 15,
    height: 15,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 4,
  },
  emailIconText: {
    fontSize: 10,
    color: "#fff",
  },
  footerBottom: {
    fontSize: 8,
    textAlign: "center",
    marginTop: 4,
    color: "#fff",
  },
});
