import { useMemo } from "react";

import { Document, Image, Page, Text, View } from "@react-pdf/renderer";

import type { MaintenanceLogPdfProps } from "@/features/maintenance";
import {
  buildTeamMemberUsernameMap,
  formatMaintenanceLogAssignees,
  splitMaintenanceLogsIntoPages,
} from "@/features/maintenance";

import { maintenanceLogPdfStyles as styles } from "./maintenance-log-pdf.styles";

function cleanDescription(description: string): string {
  return description.replace(/_/g, " ");
}

export function MaintenanceLogPDFDocument({
  equipmentInfo,
  maintenanceLogs,
  teamData,
  companyInfo,
}: MaintenanceLogPdfProps) {
  const pages = useMemo(
    () => splitMaintenanceLogsIntoPages(maintenanceLogs),
    [maintenanceLogs]
  );
  const teamMap = useMemo(
    () => buildTeamMemberUsernameMap(teamData),
    [teamData]
  );

  return (
    <Document>
      {pages.map((items, pageIndex) => (
        <Page key={pageIndex} size="A4" style={styles.page} wrap={false}>
          <View style={styles.header}>
            <View>
              {companyInfo.logo ? (
                // eslint-disable-next-line jsx-a11y/alt-text
                <Image src={companyInfo.logo} style={styles.logo} />
              ) : (
                <View style={styles.noLogo}>
                  <Text style={styles.noLogoText}>No Logo</Text>
                </View>
              )}
            </View>
            <View>
              <Text style={styles.maintenanceTitle}>Maintenance Log</Text>
            </View>
          </View>

          <View style={styles.equipmentInfo}>
            <Text style={styles.equipmentName}>{equipmentInfo.name}</Text>
            <Text style={styles.equipmentDetail}>
              Serial Number: {equipmentInfo.serial_number}
            </Text>
            {equipmentInfo.equipment_type ? (
              <Text style={styles.equipmentDetail}>
                Equipment Type: {equipmentInfo.equipment_type}
              </Text>
            ) : null}
          </View>

          <View style={styles.table} wrap={false}>
            <View style={styles.tableHeader}>
              <Text style={[styles.th, styles.thDate]}>Date</Text>
              <Text style={[styles.th, styles.thDesc]}>Description</Text>
              <Text style={[styles.th, styles.thAssigned]}>Assigned To</Text>
            </View>
            {items.map((log, idx) => (
              <View
                key={`${log.date}-${idx}`}
                style={idx % 2 === 0 ? styles.tableRow : styles.tableRowEven}
                wrap={false}
              >
                <Text style={[styles.td, styles.tdDate]}>{log.date}</Text>
                <View style={[styles.td, styles.tdDesc]}>
                  <Text style={styles.descText}>
                    {cleanDescription(log.description)}
                  </Text>
                </View>
                <Text style={[styles.td, styles.tdAssigned]}>
                  {formatMaintenanceLogAssignees(
                    log.assigned_to ?? null,
                    teamMap
                  )}
                </Text>
              </View>
            ))}
          </View>

          <View style={styles.footer}>
            <View style={styles.footerBar}>
              <View style={styles.footerContent}>
                <View style={styles.footerLeft}>
                  <View style={styles.ffLogo}>
                    <Text style={styles.ffLogoText}>FF</Text>
                  </View>
                  <Text style={{ marginLeft: 8, fontSize: 12, color: "#fff" }}>
                    fieldflow360.com
                  </Text>
                </View>
                {companyInfo.email ? (
                  <View style={styles.footerRight}>
                    <View style={styles.emailIcon}>
                      <Text style={styles.emailIconText}>@</Text>
                    </View>
                    <Text style={{ fontSize: 12, color: "#fff" }}>
                      {companyInfo.email}
                    </Text>
                  </View>
                ) : null}
              </View>
              <Text style={styles.footerBottom}>
                This maintenance log was generated by{" "}
                <Text style={{ fontWeight: "bold" }}>FieldFlow360</Text>
              </Text>
            </View>
          </View>
        </Page>
      ))}
    </Document>
  );
}
