export const BATTERY_LIFETIME_OPTIONS = [
  { id: "1.0", label: "1 year" },
  { id: "1.5", label: "1.5 years" },
  { id: "2.0", label: "2 years" },
  { id: "2.5", label: "2.5 years" },
  { id: "3.0", label: "3 years" },
  { id: "3.5", label: "3.5 years" },
  { id: "4.0", label: "4 years" },
  { id: "4.5", label: "4.5 years" },
  { id: "5.0", label: "5 years" },
  { id: "5.5", label: "5.5 years" },
  { id: "6.0", label: "6 years" },
  { id: "6.5", label: "6.5 years" },
  { id: "7.0", label: "7 years" },
  { id: "7.5", label: "7.5 years" },
  { id: "8.0", label: "8 years" },
  { id: "8.5", label: "8.5 years" },
  { id: "9.0", label: "9 years" },
  { id: "9.5", label: "9.5 years" },
  { id: "10.0", label: "10 years" },
] as const;
