"use client";

/**
 * Shared chrome for the local prototyping hub (/hub, /design-system, /flows/*).
 * Kept deliberately framework-neutral (standard Tailwind classes only) so it
 * doesn't depend on org-ui's custom token utilities being generated by the CMS
 * Tailwind build. The org-ui COMPONENTS shown inside still theme themselves.
 */
import Link from "next/link";
import { ReactNode } from "react";

const NAV = [
  { href: "/hub", label: "Hub" },
  { href: "/design-system", label: "Design System" },
  { href: "/flows", label: "Flows" },
];

export function PrototypeChrome({
  title,
  subtitle,
  active,
  children,
}: {
  title: string;
  subtitle?: string;
  active?: string;
  children: ReactNode;
}) {
  return (
    <div className="min-h-screen bg-zinc-50 text-zinc-900 dark:bg-zinc-950 dark:text-zinc-100">
      <header className="sticky top-0 z-20 border-b border-zinc-200 bg-white/80 backdrop-blur dark:border-zinc-800 dark:bg-zinc-900/80">
        <div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-6 py-3">
          <div className="flex items-center gap-3">
            <Link
              href="/hub"
              className="flex items-center gap-2 font-semibold tracking-tight"
            >
              <span className="grid h-7 w-7 place-items-center rounded-md bg-zinc-900 text-xs font-bold text-white dark:bg-white dark:text-zinc-900">
                FF
              </span>
              FieldFlow360 · Prototyping
            </Link>
          </div>
          <nav className="flex items-center gap-1 text-sm">
            {NAV.map((item) => {
              const isActive = active === item.href;
              return (
                <Link
                  key={item.href}
                  href={item.href}
                  className={
                    "rounded-md px-3 py-1.5 transition-colors " +
                    (isActive
                      ? "bg-zinc-900 text-white dark:bg-white dark:text-zinc-900"
                      : "text-zinc-600 hover:bg-zinc-100 dark:text-zinc-400 dark:hover:bg-zinc-800")
                  }
                >
                  {item.label}
                </Link>
              );
            })}
            <a
              href="/organizations/1/dashboard"
              className="ml-2 rounded-md border border-zinc-300 px-3 py-1.5 text-zinc-700 transition-colors hover:bg-zinc-100 dark:border-zinc-700 dark:text-zinc-300 dark:hover:bg-zinc-800"
            >
              Open CMS ↗
            </a>
          </nav>
        </div>
      </header>

      <main className="mx-auto max-w-6xl px-6 py-10">
        <div className="mb-8">
          <h1 className="text-3xl font-bold tracking-tight">{title}</h1>
          {subtitle ? (
            <p className="mt-2 max-w-2xl text-zinc-600 dark:text-zinc-400">
              {subtitle}
            </p>
          ) : null}
        </div>
        {children}
      </main>
    </div>
  );
}

export function PrototypeCard({
  href,
  external,
  title,
  description,
  badge,
}: {
  href: string;
  external?: boolean;
  title: string;
  description: string;
  badge?: string;
}) {
  const inner = (
    <div className="group h-full rounded-xl border border-zinc-200 bg-white p-6 shadow-sm transition-all hover:border-zinc-300 hover:shadow-md dark:border-zinc-800 dark:bg-zinc-900 dark:hover:border-zinc-700">
      <div className="mb-2 flex items-center justify-between">
        <h3 className="text-lg font-semibold">{title}</h3>
        {badge ? (
          <span className="rounded-full bg-zinc-100 px-2.5 py-0.5 text-xs font-medium text-zinc-600 dark:bg-zinc-800 dark:text-zinc-400">
            {badge}
          </span>
        ) : null}
      </div>
      <p className="text-sm text-zinc-600 dark:text-zinc-400">{description}</p>
      <span className="mt-4 inline-block text-sm font-medium text-zinc-900 group-hover:underline dark:text-zinc-100">
        Open →
      </span>
    </div>
  );

  if (external) {
    return (
      <a href={href} className="block">
        {inner}
      </a>
    );
  }
  return (
    <Link href={href} className="block">
      {inner}
    </Link>
  );
}

export function GallerySection({
  title,
  description,
  children,
}: {
  title: string;
  description?: string;
  children: ReactNode;
}) {
  return (
    <section className="mb-12">
      <div className="mb-4 border-b border-zinc-200 pb-2 dark:border-zinc-800">
        <h2 className="text-xl font-semibold">{title}</h2>
        {description ? (
          <p className="mt-1 text-sm text-zinc-500 dark:text-zinc-400">
            {description}
          </p>
        ) : null}
      </div>
      <div className="rounded-xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900">
        {children}
      </div>
    </section>
  );
}
